// packages/react/src/components/NodeList.tsx
import type { Nodes } from 'hast'
import { Fragment } from 'react'

import type { NodeListProps } from '../types.ts'

function getNodeKey(node: Nodes, idx: number, prefix = '') {
    if (node.type === 'text') {
        return `${prefix}${node.type}-${idx}`
    }

    if (node.type === 'element') {
        return `${prefix}${node.type}-${node.tagName}-${idx}`
    }

    return `${prefix}${node.type}-${idx}`
}

export default function NodeList({
    nodes,
    nodeKey,
    deep = 0,
    parentNode,
    components,
    transition: _transition,
}: NodeListProps) {
    const nodeKeyPrefix = nodeKey ? `${nodeKey}.` : ''

    return nodes.map((node, idx) => {
        const key = getNodeKey(node, idx, nodeKeyPrefix)
        const commonProps = {
            nodeIdx: idx,
            deep: deep + 1,
            nodeKey: key,
            parentNode,
        }

        if (node.type === 'text') {
            const TextComponent = (components.text ?? components.default)!
            return (
                <Fragment key={key}>
                    <TextComponent element={node} {...commonProps} />
                </Fragment>
            )
        }

        if (node.type === 'element') {
            const ElementComponent = (components[node.tagName] ?? components.default)!
            return (
                <Fragment key={key}>
                    <ElementComponent element={node} {...commonProps} />
                </Fragment>
            )
        }

        const FallbackComponent = components.default!
        return (
            <Fragment key={key}>
                <FallbackComponent element={{ type: 'element', tagName: 'span', properties: {}, children: [] }} {...commonProps} />
            </Fragment>
        )
    })
}

// packages/vue/src/components/NodeList.vue
<script setup lang="ts">
import type { Nodes } from "hast";

import { computed, h, Transition as VueTransition } from "vue";

import type { NodeListProps } from "../types";

import { useMarkdown } from "../composables/markdown";

defineOptions({
  inheritAttrs: false,
});

const { nodes, nodeKey, deep = 0, parentNode } = defineProps<NodeListProps>();

const { components, transition } = useMarkdown();

const getRenderNode = ({ node, idx, nodeKey }: { node: Nodes; idx: number; nodeKey: string }) => {
  if (node.type === "text") {
    return node.value;
  } else if (node.type === "element") {
    const component = components.value[node.tagName];
    if (!component) {
      return [];
    }
    return h(component, {
      element: node,
      nodeIdx: idx,
      deep: deep + 1,
      nodeKey,
      parentNode,
    });
  } else {
    return [];
  }
};

const nodeRenderer = ({ node, idx, nodeKey }: { node: Nodes; idx: number; nodeKey: string }) => {
  const renderNode = getRenderNode({ node, idx, nodeKey });

  if (transition.value) {
    const transitionProps = {
      appear: true,
    };
    if (typeof transition.value === "object") {
      Object.assign(transitionProps, transition.value);
    }
    return h(VueTransition, transitionProps, () => renderNode);
  }

  return renderNode;
};

const nodeKeyPrefix = computed(() => (!nodeKey ? "" : `${nodeKey}.`));

function getNodeKey(node: Nodes, idx: number) {
  if (node.type === "text") {
    return `${nodeKeyPrefix}${node.type}-${idx}`;
  } else if (node.type === "element") {
    return `${nodeKeyPrefix}${node.type}-${node.tagName}-${idx}`;
  } else {
    return `${nodeKeyPrefix}${node.type}-${idx}`;
  }
}
</script>

<template>
  <template v-for="(node, idx) in nodes" :key="getNodeKey(node, idx)">
    <nodeRenderer :node="node" :idx="idx" :nodeKey="getNodeKey(node, idx)" />
  </template>
</template>
